version: "3"

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - $HOME/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_DB: on-boarding
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    volumes:
      - $HOME/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes", "--loglevel", "verbose"]
    ports:
      - 6379:6379
    volumes:
      - $HOME/redis/data:/data

  redis-admin:
    image: erikdubbelboer/phpredisadmin
    restart: always
    environment:
      ADMIN_USER: admin
      ADMIN_PASS: admin
      REDIS_1_HOST: redis
      REDIS_1_NAME: sites-api
    ports:
      - 8081:80
    links:
      - redis
